sudo: false
language: erlang
otp_release:
  - R16B02
  - R16B01
  - R16B
  - R15B01
  - R15B
  - R14B04
  - R14B03
  - 17.0
  - 18.0
before_script:
  - hostname -f
  - cc -v
  - ld -v
script: "make travis"
